services:
  - type: web
    name: smart-attendance
    runtime: node
    plan: free
    buildCommand: prisma generate && prisma db push && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-attendance-db
          property: connectionString
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        property: host
      - key: NODE_ENV
        value: production

databases:
  - name: smart-attendance-db
    plan: free
